plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.pool.readio'
version = '0.0.1-SNAPSHOT'
description = 'readio-auth'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':readio-common')
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    // Web & Security
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // OAuth2 Authorization Server
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    // 基础设施（可按需精简）
    implementation libs.spring.boot.starter.data.redis
    implementation libs.nacos.discovery
    implementation libs.nacos.config
    implementation libs.spring.cloud.starter.openfeign
    implementation libs.spring.cloud.starter.loadbalancer
    implementation libs.commons.pool2
    implementation libs.spring.boot.admin.client
    implementation libs.postgresql
    implementation libs.hutool
    implementation libs.lombok
    implementation libs.knife4j.gateway
    implementation libs.knife4j.openapi3.jakarta
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.named('test') {
    useJUnitPlatform()
}
